# Generated by Django 2.1.3 on 2018-11-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management', '0002_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='charge',
            field=models.CharField(max_length=100),
        ),
    ]
